<?php
return [
    'If deleted your option will be remove but not disappear from your product' => 'หลังจากลบตัวเลือกแล้ว ตัวเลือกจะไม่ถูกนำออกจากสินค้า',
    'If deleted your attribute will be remove but not disappear from your product' => 'หลังจากลบคุณสมบัติแล้ว คุณสมบัติจะไม่ถูกนำออกจากสินค้า',
    'Menu Attribute' => 'เมนูคุณสมบัติสินค้า',
    'Choose Attribute' => 'เลือกคุณสมบัติสินค้า',
    'Go to {link} to add more attribute' => 'ไปยัง {link} เพื่อเพิ่มคุณสมบัติสินค้า',
    'Use only a-Z, 0-9' => 'กรุณาใช้ตัวอักษร a-Z, 0-9 เท่านั้น',
    'Invalid' => 'ข้อมูลไม่ถูกต้อง',
    'This attribute code has already' => 'รหัสตัวเลือกนี้ถูกใช้ไปแล้ว',
    'Attribute Info' => 'รายละเอียดคุณสมบัติ',
    'New Attribute' => 'เพิ่มคุณสมบัติ',
    'New Option' => 'เพิ่มตัวเลือกคุณสมบัติ',
    'Edit Attribute' => 'แก้ไขคุณสมบัติ',
    'Attribute' => 'คุณสมบัติสินค้า',
    'Attribute Name' => 'ชื่อคุณสมบัติ',
    'Attribute List' => 'รายการคุณสมบัติสินค้า',
    'Attribute Option' => 'ตัวเลือกคุณสมบัติ',
    'Option Name' => 'ชื่อตัวเลือก',
    'Option Code' => 'รหัสตัวเลือก',
    'Option List' => 'รายการตัวเลือก',
    'Code' => 'รหัสคุณสมบัติ',
    'Image' => 'รูปภาพ',
    'Product' => 'สินค้า',
    'Action' => 'ดำเนินการ',
    'View' => 'ดูคุณสมบัติ',
    'Edit' => 'แก้ไขคุณสมบัติ',
    'Delete' => 'ลบคุณสมบัติ',
    'Delete Option' => 'ลบตัวเลือก',
    'Delete Attribute' => 'ลบคุณสมบัติ',
    'Save' => 'บันทึก',
];