<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Disable selected'=>'ปิดการใช้งานที่เลือก',
	'Unknown' => 'ไม่ระบุ',
	'Created Date' => 'วันที่สร้าง',
	'Updated Date' => 'วันที่แก้ไข',
	'Billing Address' => 'ที่อยู่ใบกํากับภาษี',
	'Shipping Address' => 'ที่อยู่ที่จัดส่ง',
	'Customer List' => 'รายการลูกค้า',
	'Pre-order' => 'สั่งซื้อล่วงหน้า',
	'Day' => 'วัน',
	'Blacklist' => 'แบล็คลิส',
	'Blacklist Note' => 'หมายเหตุ',
	'Customer' => 'ลูกค้า',
	'Customer Name' => 'ชื่อ-สกุล ลูกค้า',
	'Customer Info' => 'รายละเอียดลูกค้า',
	'Bulk Actions' => 'เลือกทำทั้งหมด',
	'Add New Customer' => 'เพิ่มข้อมูลลูกค้า',
	'Edit' => 'แก้ไขลูกค้า',
	'Delete' => 'ลบลูกค้า',
	'Ch.' => 'ช่องทางการขาย',
	'Social Name' => 'ชื่อโซเชียล',
	'Name' => 'ชื่อ',
	'Full Name' => 'ชื่อ-สกุล',
	'Telephone' => 'เบอร์โทรศัพท์',
	'Email' => 'อีเมล',
	'Status' => 'สถานะ',
	'Orders History' => 'ประวัติการสั่งซื้อ',
	'Order No' => 'คำสั่งซื้อ',
	'Orders' => 'จำนวนคำสั่งซื้อ',
	'Total' => 'ยอดสั่งซื้อ',
	'Carrier' => 'ผู้จัดส่ง',
	'Order Date' => 'วันที่สั่งซื้อ',
	'Export Customers' => 'ส่งออกข้อมูลลูกค้า',
	'Disable Customers' => 'ปิดการใช้งาน',
	'Create Customer' => 'เพิ่มรายการลูกค้า',
	'Create At' => 'วันที่สร้าง',
	'Edit Customer' => 'แก้ไขรายการลูกค้า',
	'Customer Code' => 'รหัสลูกค้า',
	'surname' => 'นามสกุล',
	'ID Card' => 'เลขประจำตัวประชาชน',
	'Facebook' => 'เฟสบุ๊ค',
	'Line' => 'ไลน์',
	'Note' => 'บันทึก',
	'Status' => 'สถานะ',
	'Customer Address' => 'ที่อยู่ลูกค้า',
	'Address Line' => 'ที่อยู่',
	'Zipcode' => 'รหัสไปรษณีย์',
	'Search' => 'ค้นหา',
	'Search by Name, Telephone Or Email ...' => 'ค้นหาด้วยชื่อ, เบอร์โทรศัพท์ หรืออีเมลล์ ...',
	'Save' => 'บันทึกรายการ',
	'Cancel' => 'ยกเลิกรายการ',
	'Customer#,name' => 'ค้นหารายชื่อลูกค้า',
	'Channel' => 'ช่องทางขาย',
    'All Channels' => 'ช่องทางขายทั้งหมด',
	'Channels Sync' => 'ช่องทางขายทที่เข้ามาอัตโนมัติ',
	'Channels UnSync' => 'ช่องทางขายทที่ไม่ได้นำเข้าอัตโนมัติ',
	'Valid telephone nubmer example 0614207877 or 0246255934' => 'หมายเลขโทรศัพท์ที่ถูกต้อง ตัวอย่าง 0614207877 หรือ 0246255934',
	'Valid email format example info@xcommerce.co.th' => 'รูปแบบอีเมลล์ที่ถูกต้อง เช่น info@xcommerce.co.th',
	'You Confirm Password must be equal to Password' => 'รหัสผ่านยืนยันไม่ตรงกับรหัสผ่าน',
	'At least {0} characters required!' => 'ควรมีอย่างน้อย {0} ตัว!',
	'No more than {0} characters required!' => 'ไม่ควรมีเกิน {0} ตัว!',
	'Must be numeric only!' => 'ควรเป็นตัวเลขเท่านั้น!',
 	'Select Channel ...' => 'เลือกช่องทางขาย ...',
	'Name and Surname ...' => 'ชื่อ-สกุลลูกค้า ...',
	'Social name from facebook or line platform ...' => 'ชื่อโซเชียลลูกค้า ที่มาจากช่องทาง Faceook หรือ Line ...',
	'Telephone number ...' => 'เบอร์โทรศัพท์ ...',
	'Customer shipping address ...' => 'ที่อยู่จัดส่ง ...',
	'Blacklist note ...' => 'หมายเหตุ ...',
	'Zipcode ...' => 'รหัสไปรษณีย์ ...',
	'Please input alphabet characters only.' => 'กรุณาพิมพ์ตัวอักษรเท่านั้น',
	'ID card number ...' => 'เลขบัตรประชาชน ...',
	'Email address ...' => 'อีเมลล์ลูกค้า ...',
	'This field is required.' => 'ไม่ควรเป็นค่าว่าง',
	'Please enter a valid email address.' => 'กรุณาพิมพ์รูปบแบบอีเมลล์ให้ถูกต้อง!',
	'Your ID Card/Passport must be numeric.' => 'หมายเลขบัตรประชาชนควรจะเป็นตัวเลขเท่านั้น!',
	'Please enter a valid phone number!' => 'กรุณากรอกหมายเลขโทรศัพท์ให้ถูกต้อง!',
	'Export All to CSV' => 'ส่งออกทั้งหมดในรูปแบบ CSV',
	'Add New Order' => 'เพิ่มคำสั่งซื้อ',
	'Are you want to delete {0} ?' => 'คุณต้องการลบลูกค้าชื่อ {0} ?',
	'Customer is deleted' => 'ลบข้อมูลเรียบร้อย',
	'Leadpage Data' => 'ข้อมูล Leadpage',
];
