<?php
return [
    'Ch.' => 'ช่องทาง',
    'Image' => 'รูปภาพ',
    'Report All' => 'รายงานทั้งหมด',
    'Search' => 'ค้นหา',
    'Select' => 'เลือก',
    'From ...' => 'ตั้งแต่ ...',
    'To ...' => 'จนถึง​ ...',
    'Shipment Drop Off Report' => 'รายงานสรุปการจัดส่งแบบ Drop Off',
    'Search Order NO., Sender, Receiver, Tracking ...' => 'ค้นหาด้วยหมายเลขคำสั่งซื้อ, ผู้ส่ง, ผู้รับ หรือหมายเลขพัสดุ ...',
    'Processing' => 'กำลังดำเนินการ',
    'Complete' => 'เสร็จสิ้น',
    'Receiver Province ({0})' => 'ปลายทาง ({0})',
    'Sender Province ({0})' => 'ต้นทาง ({0})',
    'Receiver Province' => 'ปลายทาง',
    'Sender Province' => 'ต้นทาง',
    'Sender Prov.' => 'ต้นทาง',
    'Receiver Prov.' => 'ปลายทาง',
    'Notice' => 'หมายเหตุ',
    'Data will be update exactly rate and weight at 7.00 PM' => 'ข้อมูลจะอัพเดทค่าใช้จ่ายจริง ทุกวัน เวลาประมาณ 19.00 น.',
    'Order No.' => 'หมายเลขคำสั่งซื้อ',
    'Sender' => 'ผู้ส่ง',
    'Receiver' => 'ผู้รับ',
    'Tracking No.' => 'หมายเลขพัสดุ',
    'Click for check tracking' => 'คลิ๊กเพื่อตรวจสอบหมายเลขพัสดุ',
    'Zipcode {0}' => 'รหัสไปรษณีย์ {0}',
    'Seller Weight' => 'น้ำหนักที่ระบุ',
    'Seller Price' => 'ราคาที่ระบุ',
    'Actual Weight' => 'น้ำหนักจริง',
    'Actual Price' => 'ราคาจริง',
    'Created At' => 'วันที่ดำเนินการ',
    'Sent Date' => 'วันที่ส่ง',
    'Status' => 'สถานะการจัดส่ง',
];