<?php
return [
    'Edit' => 'แก้ไข',
    'Save' => 'บันทึก',
    'Link' => 'ลิงค์',
    'Modify' => 'แก้ไขล่าสุด',
    'Published' => 'เผยแพร่',
    'Unpublished' => 'ไม่เผยแพร่',
    'Beta' => 'เบต้า',
    'Done' => 'เสร็จสิ้น',
    'Listing' => 'ลิสติ้ง',
    'Name, Sku or Description' => 'ชื่อสินค้า รหัสสินค้า หรือรายละเอียดสินค้า',
    'Filter' => 'กรองข้อมูล',
    'Status' => 'สถานะ',
    'Linked' => 'เชื่อมต่อแล้ว',
    'Unlinked' => 'ไม่เชื่อมต่อ',
    'Dont have any map item on this channel' => 'ไม่พบการเชื่อมต่อสินค้า ไปยังช่องทางขายนี้',
    'Not found head of this variation' => 'ไม่พบข้อมูลสินค้าต้น (config) ของสินค้าตัวนี้',
    'Option update stock has been disabled' => 'ไม่สามารถอัพเดทสต๊อกได้ เนื่องจากปิดอัพเดทสต๊อก',
    'Request failed to {channel}, Try again' => 'พบข้อผิดพลาดในการเชื่อมต่อไปยังช่องทางขาย {channel} กรุณาลองใหม่อีกครั้ง',
    'Error {msg}' => 'พบข้อผิดพลาด {msg}',
    "Variations' price differences exceeds the limitation of your shop's market area." => 'ไม่สามารถตั้งราคาสินค้า ห่างกันเกิน 5 เท่าของราคาสินค้าต่ำสุด',
];