<?php
return [
	'Clear'=> 'ยกเลิก',
    'Fulfill By'=>'การดำเนินการ',
	'Shipment'=> 'การจัดส่ง',
	'For faster and easier search. Example of search queries, such as first name, last name, social name, telephone number or tracking number' => 'เพื่อให้รวดเร็วและง่ายขึ้น ขอแนะนำให้ค้นหาด้วยชื่อ,​ สกุล, ชื่อโซเชียล,​ เบอร์โทรศัพท์ หรือหมายเลขพัสดุ',
	'Not Allowed' => 'ไม่อนุญาต',
	'Please dont search by full url link' => 'ขอความร่วมมือไม่ค้นหาข้อมูลด้วยลิงค์เว็ปไซต์',
	'Customer not found.' => 'ไม่พบข้อมูลลูกค้า',
	'Can edit tracking number untill your item registered in logistics' => 'สามารถแก้ไขหมายเลขติดตามพัสดุได้ จนกว่าสินค้าของท่านจะถูกลงทะเบียนเข้าระบบที่บริษัทขนส่ง ที่ท่านจัดส่ง',
	'Manual' => 'ระบุวันที่',
	'Please try agian or Refresh this page' => 'กรุณาลองใหม่อีกครั้ง หรือกด Refresh หน้านี้',
	'Already Confirm' => 'ยืนยันแล้ว',
	'{order} cancel is complete' => 'ยกเลิกคำสั่งซื้อ {order} เสร็จสิ้น',
	'{order} cannot return reserv to stock' => 'คำสั่งซื้อ {order} ไม่สามารถคืนสถานะจองสินค้าได้',
	'{order} cannot return item to stock' => 'คำสั่งซื้อ {order} ไม่สามารถคืนสินค้าได้',
	'{name} not enough serial, Please check your serial code' => 'สินค้า​ {name} มีจำนวนหมายเลขผลิตภัณฑ์ไม่เพียงพอ',
	'By {admin}' => 'โดย {admin}',
	'System' => 'ระบบ',
	'Not Enough' => "สินค้าไม่เพียงพอ",
	'Not enough stock, Please contact warehouse' => 'จำนวนสินค้าไม่เพียงพอต่อการขาย กรุณาติดต่อฝ่ายคลังสินค้า',
	'{0} Not Enough. Balance {1}' => 'สินค้า {0} ไม่พอขาย คงเหลือ {1} ชิ้น',
	'Not found tracking number.' => 'ไม่มีหมายเลขส่งพัสดุ',
	'Change Warehouse' => 'เปลี่ยนคลังสินค้า',
	'Change selected warehouse. Current ordered item will be clear !.' => 'การเปลี่ยนคลังสินค้า จำเป็นต้องเลือกสินค้าใหม่ !',
	'Something Wrong, Please try again !' => 'พบข้อผิดพลาด กรุณาลองใหม่อีกครั้ง !',
	'Not found product in {0} warehouse' => 'ไม่พบสินค้าในคลัง {0}',
	'Search By' => 'ค้นหาวันที่โดย',
	'Order Date' => 'วันที่ขาย',
	'Created' => 'วันที่ขาย',
	'Confirmed/RTS' => 'ยืนยัน/พร้อมจัดส่ง',
	'Today' => 'วันนี้',
	'Delivery' => 'วันที่รับสินค้า',
	'Promptly' => 'พร้อมรับทันที',
	'Add Payment' => 'แจ้งชำระเงิน',
	'Confirm Payment' => 'ยืนยันการชำระเงิน',
	'Add new shipping address.' => 'เพิ่มที่อยู่จัดส่งสินค้า',
	'Add new billing address.' => 'เพิ่มที่อยู่สำหรับออกใบกำกับภาษี',
	'Shipping Address Not Set' => 'ไม่พบข้อมูลที่อยู่จัดส่งสินค้า',
	'Billing Address Not Set' => 'ไม่พบข้อมูลที่อยู่จัดส่งสินค้า',
	'-' => 'ถึง',
	'Please wait payment loading ...' => 'กรุณารอซักครู่ กำลังโหลดข้อมูล ...',
	'Please wait ...' => 'กรุณารอซักครู่ กำหลังโหลดข้อมูล ...',
	'Add Product' => 'เพิ่มสินค้า',
	'Choose Product' => 'เลือกสินค้า',
	'Recent' => 'ล่าสุด',
	'All Product' => 'สินค้าทั้งหมด',
	'Search' => 'ค้นหา',
	'Select' => 'เลือกสินค้านี้',
	'Select Orders' => 'เลือกสินค้าหลายรายการ',
	'Cannot select this product becuase your store not allow to minus stock' => 'ไม่สามารถเลือกสินค้าได้ เนื่องจากไม่อนุญาติให้สินค้าน้อยกว่า 0 กรุณาติดต่อเจ้าของร้าน',
	'Cannot Add Product' => 'ไม่สามารถเลือกสินค้าได้',
	'Save & Add New' => 'บันทึก และสร้างใหม่',
	'Your data not found ...' => 'ไม่พบข้อมูลที่คุณค้นหา ...',
	'Copy' => 'สำเนา',
	'Total' => 'รวมเงิน',
	'Shipping Price' => 'ค่าจัดส่ง',
	'Amount' => 'จำนวน',
	'Confirmed' => 'ยืนยันแล้ว',
	'Shipping' => 'ค่าขนส่ง',
	'Vat 7%' => 'ภาษีมูลค่าเพิ่ม 7%',
	'Grand Total' => 'จำนวนเงินรวมทั้งหมด',
	'Confirm this payment (Create invoice and order status in your website imediatly)' => 'ยืนยันการชำระเงิน (สร้างใบส่งสินค้า และเปลี่ยนสถานะคำสั่งซื้อบนเว็ปไซต์ของท่านทันที)',
	'Press enter to search customer detail.' => 'กด Enter เพื่อค้นหาข้อมูลลูกค้า',
	'Cannot Search Customer' => 'ไม่สามารถค้นหาข้อมูลได้',
	'Please fill text less one charactor.' => 'กรุณากรอกข้อมูลเพื่อค้นหา',
	'Unknow or no payment' => 'ไม่รู้จัก หรือไม่ได้ระบุวิธีการชำระเงิน',
	'Vat are shipping price included' => 'ภาษีมูลค่าเพิ่มนี้ รวมค่าขนส่ง',
	'Vat are cod price included' => 'ภาษีมูลค่าเพิ่มนี้ รวมค่าบริการเก็บเงินปลายทาง',

	//shioping
	'Flat Rates' => 'ค่าขนส่งคงที่',
	'Table Rate By Item' => 'ค่าส่งตามจำนวนสินค้า',

	'Others' => 'รูปแบบการจัดส่งอื่นๆ',

	'Data is invalid' => 'ข้อมูลไม่ถูกต้อง, กรุณาตรวจสอบอีกครั้งค่ะ',
];
