<?php
return [
    'Order confirmed will be complete automatic in setting day' => 'คำสั่งซื้อที่กำลังจัดส่ง จะถูกย้ายไปสถานะสำเร็จโดยอัตโนมัติตามจำนวนวันที่ตั้งค่า',
    'Complete' => 'คำสั่งซื้อสำเร็จ',
    'Manual' => 'ดำเนินการด้วยตนเอง',
    'Past 3 days' => 'หลังจากจัดส่ง 3 วัน',
    'Past 7 days' => 'หลังจากจัดส่ง 7 วัน',
    'Past 14 days' => 'หลังจากจัดส่ง 14 วัน',
    'Tax' => 'ภาษี',
    'Order Tax' => 'ภาษีคำสั่งซื้อ',
    'Product Tax' => 'ภาษีสินค้า',
    'Notification' => 'การแจ้งเตือน',
    'COD' => 'บริการเก็บเงินปลายทาง',
    'Logo' => 'โลโก้',
    'Payment' => 'การชำระเงิน',
    'COD Services' => 'ผู้ให้บริการ',
    'Description' => 'คำอธิบาย',
    'Service Fee' => 'ค่าบริการ',
    'Status' => 'สถานะ',
    'Save' => 'บันทึก',
    //kerry name of service,
    'Kerry 2 Days' => 'Kerry 2 Days',
    'Kerry Bangkok Sameday' => 'Kerry Bangkok Sameday',
    //store payment
    'Alpha Delivers Nationwide for eCommerce' => 'อัลฟ่า ส่งทั่วไทย สำหรับสินค้าออนไลน์',
    'Kerry Express is Thailand Leading Parcel Delivery' => 'เคอรี่ เอ็กซ์เพรส บริษัทจัดส่งพัสดุชั้นนำของประเทศไทย',
    'Kerry Bangkok Sameday is service same-day document and small parcel delivery service' => 'Bangkok Sameday คือบริการรูปแบบใหม่ภายในพื้นที่กรุงเทพฯ โดยเน้นการจัดส่งเอกสารและพัสดุขนาดเล็กภายในวันเดียวเท่านั้น',
    'Kerry 2 Days is service document and small parcel delivery service within 2 days' => 'Kerry 2 Days คือบริการพิเศษสำหรับการจัดส่งพัสดุภายใน 2 วัน',
    'Cannot Change !' => 'ไม่สามารถเปลี่ยนได้ !',
    'You need to confirm order all has reserved before change' => 'คุณต้องยืนยันคำสั่งซื้อ ก่อนเปลี่ยรูปแบบการตัดสต๊อก',
    'Found {0} orders has reserved. You need to confirm order all has reserved before change' => 'พบ {0} สินค้าที่มีการจองสินค้า กรุณายืนยันคำสั่งซื้อก่อนเปลี่ยนรูปแบบการตัดสต๊อก',
    'Ok' => 'ยืนยัน',
    'Order Reserved' => 'คำสั่งซื้อที่มีการจองคงค้าง',
    'Include Shipping' => 'รวมค่าขนส่ง',
    'Include COD Fee' => 'รวมค่าบริการชำระเงินปลายทาง',
    'Enjoy the ease of fast, affordable and reliable express and tracking service on your mobile devices. Download now!' => 'สามารถให้บริการรวดเร็ว มีประสิทธิภาพ และสามารถติดตามสถานะพัสดุได้ตลอดเวลา พร้อมรับส่วนลดโปรโมชั่นต่างๆอีกมากมาย มาโหลด Flash Express App กันเถอะ',
    'Create Order' => 'สร้างออเดอร์',
    'Cancel Order' => 'ยกเลิกคำสั่งซื้อ',
    'Tracking Order' => 'เลขแทร็คกิ้ง',
    'Default' => 'ค่าเริ่มต้น',
    'Is in "Shipping" status for 1 day' => 'อยู่ในสถานะ "กำลังจัดส่ง" แล้ว 1 วัน',
    'Is in "Shipping" status for 3 days' => 'อยู่ในสถานะ "กำลังจัดส่ง" แล้ว 3 วัน',
    'Is in "Shipping" status for 7 days' => 'อยู่ในสถานะ "กำลังจัดส่ง" แล้ว 7 วัน',
    'Is in "Shipping" status for 14 days' => 'อยู่ในสถานะ "กำลังจัดส่ง" แล้ว 14 วัน',
];