<?php
return [
    'Confirm' => 'ยืนยัน',
    'Close' => 'ปิด',
    'Edit Stock' => 'แก้ไขสต๊อก',
    'Inventory' => 'สินค้าคงคลัง',
    'Status' => 'สถานะ',
    'Remark' => 'หมายเหตุ',
    'QTY' => 'คงเหลือ',
    'Reserved' => 'จอง',
    'On Hand' => 'พร้อมขาย',
    'Search by Product SKU Or Name ...' => 'ค้นหาสินค้าโดย รหัสสินค้า หรือชื่อสินค้า ...',
    'Stock Blance' => 'สินค้าคงคลัง',
    'Select Start Date ...' => 'เลือกวันเริ่มต้น ...',
    'Select End Date ...' => 'เลือกวันสิ้นสุด ...',
    'Transfer' => 'ย้ายคลังสินค้า',
    'Transfer Items' => 'รายการสินค้า',
    'Current Warehouse' => 'คลังสินค้าปัจจุบัน',
    'Amount' => 'จำนวนที่ย้าย',
    'Transfer To' => 'ย้ายไปยัง',
    'Save & Transfer' => 'บันทึก และย้ายสินค้า',
    'Cannot below than {0} (Reserved)' => 'ไม่สามารถน้อยกว่า {0} (จอง)',
    'Waitting' => 'รอดำเนินการ',
    'Processing' => 'กำลังดำเนินการ',
    'Done' => 'เสร็จสิ้น',
    'Out of Stock' => 'สินค้าหมด',
    'Stock update can be done when setting a warehouse in channel same as warhouse update only' => 'การอัพเดตสต็อกสามารถทำได้เมื่อตั้งค่าคลังสินค้าในช่องทางการขาย เหมือนกับการอัพเดทสต๊อกเท่านั้น',
];
?>