<?php
return [
    'Fulfill By'=>'การดำเนินการ',
    'Create' => 'สร้าง',
    'Update' => 'แก้ไขรายการโอนสินค้า',
    'Edit' => 'แก้ไขรายการโอนสินค้า',
    'Approve' => 'ยืนยัน',
    'Add Transfer' => 'สร้างรายการโอนสินค้า',
    'Transfer' => 'โอนสินค้า',
    'Transfer Number' => 'หมายเลขการโอนสินค้า',
    'Transfer Detail' => 'รายละเอียดการโอนสินค้า',
    'Transfer List' => 'รายการโอนสินค้า',
    'Transfer Product' => 'รายการสินค้า',
    'Transfer Date' => 'วันที่โอนสินค้า',
    'Select Warehouse' => 'เลือกคลังสินค้า',
    'Search by Transfer Number' => 'ค้นหาด้วยหมายเลขการโอนสินค้า',
    'From Warehouse' => 'คลังสินค้าต้นทาง',
    'To Warehouse' => 'คลังสินค้าปลายทาง',
    'Created At' => 'วันที่สร้าง',
    'Transfer By' => 'ผู้โอน',
    'Approve By' => 'ผู้ยืนยัน',
    'Status' => 'สถานะ',
    'From' => 'คลังสินค้าปัจจุบัน',
    'To' => 'โอนไปยัง',
    'Remark' => 'หมายเหตุ',
    'Save' => 'บันทึก',
    'Product Name' => 'ชื่อสินค้า',
    'Product Name Or SKU' => 'ค้นหาด้วยชื่อ หรือรหัสสินค้า',
    'SKU' => 'รหัสสินค้า',
    'Onhand' => 'คงเหลือ',
    'Image' => 'รูปภาพ',
    'Quantity' => 'จำนวน',
    'Action' => 'ดำเนินการ',
    'Reference' => 'หมายเลขอ้างอิง',
    'No Product In This Warehouse Or Empty' => 'ไม่พบสินค้าในคลังสินค้านี้ หรือสินค้าอาจหมด',
    'Imediately, If selected will be tranfer all item and change transfer status into transfered.' => 'หากเลือก จะทำการโอนสินค้าทันที และเปลี่ยนสถานะใบโอนสินค้าเป็นโอนสินค้าเรียบร้อยแล้ว',
    'Warning' => 'คำเตือน',
    'From Warehouse and To Warehouse cannot be same.' => 'คลังสินค้าปัจจุบัน และคลังสินค้าปลายทาง ไม่ควรเป็นคลังสินค้าเดียวกัน',
    'Transfer has been cancel. Wait a moment.' => 'ยกเลิกการโอนสินค้าเสร็จสิ้น กรุณารอซักครู่',

    'Cancel Transfer' => 'ยกเลิกการโอนสินค้า',
   'If cancel your received product will be return automaticly.' => 'หากยกเลิก ระบบจะคืนสินค้ากลับอัตโนมัติ',
   'Confirm' => 'ยืนยัน',
    //
    'Cancel' => 'ยกเลิก',
    'Pending' => 'รอดำเนินการ',
    'Completed' => 'โอนสินค้าแล้ว',
    'Attachment' => 'ไฟล์แนบ',
    'View' => 'ดูรายการโอนสินค้า',
    'Print' => 'พิมพ์เอกสาร',
    'Back' => 'ย้อนกลับ',
    'Approve Form' => 'ยืนยันการโอนสินค้า',
];