<?php
return [
    'Ch.' => 'ช่องทางขาย',
    'Warehouse' => 'คลังสินค้า',
    'Confirm' => 'ยืนยัน',
    'Cancel' => 'ยกเลิก',
    'Edit' => 'แก้ไข',
    'Add' => 'เพิ่ม',
    'Delete' => 'ลบ',
    'Address' => 'ที่อยู่',
    'Add Warehouse' => 'เพิ่มคลังสินค้า',
    'Edit Warehouse' => 'แก้ไขคลังสินค้า',
    'Name' => 'ชื่อคลังสินค้า',
    'Telephone' => 'เบอร์โทรศัพท์',
    'Description' => 'รายละเอียด',
    'Default' => 'ค่าเริ่มต้น',
    'Enable' => 'เปิด',
    'Disable' => 'ปิด',
    'Status' => 'สถานะ',
    'Products' => 'สินค้าภายใน',
    'Stocks' => 'สต๊อก',
    'Date Create' => 'วันที่สร้าง',
    'Action' => 'ดำเนินการ',
    'Set as Default Warehouse' => 'ตั้งเป็นคลังสินค้าเริ่มต้น',
    'Delete Warehouse' => 'ลบคลังสินค้า',
    'Cannot Delete Warehouse' => 'ไม่สามารถลบคลังสินค้า',
    'Please transfer or delete product stock inside this warehouse' => 'กรุณาโอน/ย้ายสินค้า หรือปรับจำนวนสินค้าภายในคลังสินค้านี้ก่อน',
    'Please change your warehouse in channel setting' => 'กรุณาเปลี่ยนการตั้งค่าคลังสินค้าในช่องทางการขาย',
    'If confirm it will imediatly delete.' => 'หากตกลง ระบบจะทำการลบคลังสินค้าในทันที',
    'Your warehouse has been deleted.' => 'คลังสินค้าถูกลบเรียบร้อย',
    'Cannot Add More Warehouse' => 'ไม่สามารถเพิ่มคลังสินค้าได้',
    'Limited, Please check your package.' => 'เกินจำนวนกำหนด กรุณาตรวจสอบแพ็คเกจ',
    'Enable/Disable' => 'เปิด/ปิดคลังสินค้า',
    'Set status of warehouse' => 'ตั้งค่าเปิด/ปิดคลังสินค้า',
    'Set default warehouse' => 'ตั้งค่าคลังสินค้าเริ่มต้น',
];